# Generated by Django 2.2.4 on 2019-09-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.CharField(default='right,left,up,down', max_length=300),
            preserve_default=False,
        ),
    ]
