# Generated by Django 2.2.4 on 2019-09-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190901_1615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
