# Generated by Django 2.2.4 on 2019-09-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20190908_0637'),
        ('dict', '0002_auto_20190830_1911'),
        ('accounts', '0002_user_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quizzes',
            field=models.ManyToManyField(blank=True, to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='user',
            name='words',
            field=models.ManyToManyField(blank=True, to='dict.Word'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
